name: Nuclei - Vulnerability Scan with Issues

on:
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://www.bsi.bund.de/
          github-report: true
          github-token: ${{ secrets.TOKEN }}
          flags: "-severity critical,high,medium -stats"

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log
